name: Release Hot Fix

on:
  push:
    branches-ignore:
      - changeset-release/**
      - main
    paths:
      - CHANGELOG.md

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Set user
        run: git config user.name github-actions[bot] && git config user.email github-actions[bot]@users.noreply.github.com

      - name: Publish release
        uses: changesets/action@v1
        with:
          commitMode: 'github-api'
          publish: npm run github:release
          commit: 'Create new config version'
          title: 'Create new config version'

      - name: Generate Release Curl Templates
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          GRANTS=("playground-grant" "some-grant")
          
          for GRANT in "${GRANTS[@]}"; do
            FILES=$(find "$GRANT" -type f | sed "s|^$GRANT/||" | jq -R . | jq -s -c .)
            
            echo "------------------------------------------------------------"
            echo "Release template for $GRANT (version $LATEST_TAG): Use this to release to dev"
            echo "------------------------------------------------------------"
            cat <<EOF
          curl -X POST https://ephemeral-protected.api.dev.cdp-int.defra.cloud/grants-config-broker/api/release-config \\
               -H "x-api-key: <INSERT EPHERMERAL DEV KEY>" \\
               -H "Content-Type: application/json" \\
               -H "Authorization: Bearer <your_token>" \\
               -d '{
                 "grant": "$GRANT",
                 "repository": "grant-config-playground",
                 "version": "$LATEST_TAG",
                 "files": $FILES,
                 "status": "draft"
               }'
          EOF
            echo -e "\n"
          done
